# Generated by Django 4.2.14 on 2024-08-13 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_object_parent_alter_address_apartment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                db_table="objects_files_m2m",
                related_name="objects_set",
                to="tasks.attachedfile",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="groups",
            field=models.ManyToManyField(
                db_table="objects_groups_m2m",
                related_name="objects_set",
                to="tasks.objectgroup",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="objects_tags_m2m",
                related_name="objects_set",
                to="tasks.tag",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="tasks",
            field=models.ManyToManyField(
                blank=True,
                db_table="objects_tasks_m2m",
                related_name="objects_set",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="userobjectgroup",
            name="permission",
            field=models.CharField(choices=[("R", "Только чтение"), ("RW", "Чтение/Запись")], max_length=10),
        ),
    ]
