# Generated by Django 4.2.14 on 2024-08-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_object_slug_alter_object_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
