# Generated by Django 4.2.14 on 2024-08-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_object_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachedfile",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="object",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
