# Generated by Django 5.1.1 on 2024-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_objectgroup_name_alter_task_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_text",
            field=models.TextField(blank=True),
        ),
    ]
