# Generated by Django 5.1.1 on 2024-09-18 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_task_completion_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="engineers",
            field=models.ManyToManyField(
                db_table="tasks_engineers_m2m",
                related_name="tasks",
                to="tasks.engineer",
            ),
        ),
        migrations.AddField(
            model_name="engineer",
            name="departament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="engineers",
                to="tasks.departament",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="departments",
            field=models.ManyToManyField(
                db_table="tasks_departments_m2m",
                related_name="tasks",
                to="tasks.departament",
            ),
        ),
    ]
