# Generated by Django 5.1.1 on 2024-10-03 13:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_task_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="another_link",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="object",
            name="ecstasy_link",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="object",
            name="notes_link",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="object",
            name="zabbix_link",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="object",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="completion_text",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
