# Generated by Django 5.1.1 on 2024-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_object_another_link_object_ecstasy_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachedfile",
            name="is_image",
            field=models.BooleanField(default=False),
        ),
    ]
