# Generated by Django 5.1.1 on 2024-12-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_task_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.address",
            ),
        ),
    ]
