# Generated by Django 5.1.1 on 2025-02-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_comment"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS object_groups (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(128) UNIQUE NOT NULL
            );
            """
        ),
    ]
