# Generated by Django 5.1.1 on 2025-02-25 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0020_task_status_changed_by_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.CharField(default="task_completed", max_length=50),
        ),
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tasks.task",
            ),
        ),
    ]
