# Generated by Django 5.1.1 on 2025-02-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status_changed_by",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
