# Generated by Django 5.1.1 on 2025-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0021_remove_notification_message_notification_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
